### PR TITLE
GFM-31 Added JSCS and ESLint to project and refactored code to follow…

### PR DESCRIPTION
**Pull request by joefitter**
… guidelines

https://jira.digital.homeoffice.gov.uk/browse/GFM-31

* Added eslint config from https://github.com/UKHomeOffice/eslint-config-homeoffice
* Added JSCS and ESLint
* Added style and lint tasks to package.json
* Added pre-commit to run test lint and style
* Added lint and style to .travis.yml

### CODE REVIEW

**Comment by JoeChapman** [comment]
@easternbloc got any problems with this?

**Comment by easternbloc** [comment]
@JoeChapman I believe passports indent differently so I think you'd want @gavboulton approval before going any further. They may well have their own style they want to enforce. It'd be nice to get everyone onto the same settings but it needs to be discussed before merging.

**Comment by gavboulton** [comment]
We do indent differently and don't mind comma separated var declarations.

ESlint is currently on version 2 and while the Home Office linting project is still evolving I'd prefer to wait a little before adding these changes. Within the passports team we're looking at aligning all our linting, so can look at this as part of that work.

The addition of things like 'use strict' is definitely worthwhile though.

**Comment by easternbloc** [comment]
I tend to agree with @gavboulton I think we should wait till eslint-config-homeoffice is more mature (there's talk of more releases to help migrate to eslint 2.0) but it's not quite there yet

**Comment by joefitter** [comment]
👍  I vote https://github.com/feross/standard :)

**Comment by easternbloc** [comment]
@joefitter 'no semicolons' yeah lets not _go_ there.

**Comment by gavboulton** [comment]
@joefitter Are you happy for me to close this?

**Comment by easternbloc** [comment]
💥

**Pull request closed without merging**
