### PR TITLE
New release as it's been a while.

### PR DESCRIPTION
**Pull request by easternbloc**
Minor version bump for new toggle support.

### CODE REVIEW

**Comment by easternbloc** [comment]
@gavboulton we've had a few PR's go into master and we've not had a release for a little while.

**Comment by gavboulton** [comment]
Hi @easternbloc, good spot. I'll close this but do it all through NPM.

**Comment by easternbloc** [comment]
@gavboulton :+1:

**Comment by gavboulton** [comment]
Published at v1.5.0

**Comment by easternbloc** [comment]
Thanks @gavboulton

**Pull request closed without merging**
