### PR TITLE
Add validation styling to frontend toolkit

### PR DESCRIPTION
**Pull request by lennym**
Copies validation styles from pex project.

### CODE REVIEW

**Comment by lennym** [comment]
FAO @gavboulton @sebinsua

**Comment by lennym** [comment]
Not to be merged until @gavboulton's work on updating the validation styles for PEX is complete and the code can be kept in sync.

**Comment by gavboulton** [comment]
I'm happy for this to be merged. @lennym @sebinsua what do you think?

**Comment by lennym** [comment]
If there aren't any upstream changes from your PEX work, then go for it!

**Pull request merged**
