### PR TITLE
Update govuk_frontend_toolkit to latest

### PR DESCRIPTION
**Pull request by JoeChapman**
- update govuk_frontend_toolkit to 4.5.0
- update package version to with major increment (2.5.0)

### CODE REVIEW

**Comment by gavboulton** [comment]
I can update the package version and publish separately (at v2.0.0).

What are the main changes in govuk_frontend_toolkit?

**Comment by JoeChapman** [comment]
@gavboulton https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG.md describes the main differences between 3.1.0 and this latest version. 

We wanted to make sure we are using the latest CSS amendments.

**Comment by gavboulton** [comment]
Thanks @JoeChapman, the mobile first typography changes are a good one to be aware of. If you remove the version change I'll merge.

**Comment by JoeChapman** [comment]
@gavboulton removed the version number, cheers dude

**Comment by gavboulton** [comment]
Published at v2.0.0. It will be worth updating govuk_elements soon too.

**Comment by easternbloc** [comment]
:+1:

**Pull request merged**
