### PR TITLE
Make the app mac friendly

### PR DESCRIPTION
**Pull request by easternbloc**
Simple fix so I can install the toolkit on a mac.

### CODE REVIEW

**Comment by lennym** [comment]
This is fine, but do you mind removing the npm version commit, and we'll manage the versioning and publishing separately from PRs? Running `npm version` once it's in master does the tagging for us, and avoids any issues about merge order of PRs.

**Comment by easternbloc** [comment]
Sure. Will do.

**Comment by easternbloc** [comment]
Done. Cheers dude.

**Comment by lennym** [comment]
Will merge and publish once travis is done.

**Comment by lennym** [comment]
Published at v1.2.1

**Pull request merged**
