### PR TITLE
Add contain floats mixin to toolkit

### PR DESCRIPTION
**Pull request by lennym**

### CODE REVIEW

**Comment by gavboulton** [comment]
Does LSR use any separate stylesheets for any versions of IE?

**Comment by sebinsua** [comment]
^ Not the version I am working on. Not yet.

The previous LSR had their own stylesheets and lots of IE8/IE7 stylesheets (which I cannot use with the new PEX-style templates.)

**Comment by gavboulton** [comment]
I'm in the process of updating PEX to use the `%contain-floats` mixin (`@extend %contain-floats`) provided by govuk_frontend_toolkit, so I think this PR can be closed.

**Comment by lennym** [comment]
:+1:

**Pull request closed without merging**
